### PR TITLE
Migrate to use v0.14 API

### PR DESCRIPTION
**Pull request by cosmo0920**
I've tried to migrate to use v0.14 Input/Output Plugin API.
This PR contains major update change.
Could you bump up ~~minor~~ major version if releasing new version of gem?
And please refer http://docs.fluentd.org/v0.14/articles/plugin-update-from-v12 before release new version.

Thanks,

### CODE REVIEW

**Comment by kenjiskywalker** [comment]
@cosmo0920 
Sorry for the late reply 🙇 

@winebarrel 
How about do you think this PR?

**Comment by winebarrel** [comment]
> How about do you think this PR?

I think it's good. 👍 
However, I think that it is better to bump up the major version of the plugin.

**Comment by cosmo0920** [comment]
> However, I think that it is better to bump up the major version of the plugin.

Sure, I also think that bumping major version is better.

**Comment by kenjiskywalker** [comment]
@cosmo0920 

Merged! thanks for your great PR 👍

**Comment by cosmo0920** [comment]
Great! Thank you!! :yum:

**Pull request merged**
