### PR TITLE
Support label feature

### PR DESCRIPTION
**Pull request by cosmo0920**

### CODE REVIEW

**Comment by winebarrel** [comment]
This has been supported by [PR#8](https://github.com/kenjiskywalker/fluent-plugin-rds-slowlog/pull/8).

**Comment by cosmo0920** [comment]
OK, I close this PR.

**Comment by kenjiskywalker** [comment]
@cosmo0920

I'm sorry I was late!

**Comment by cosmo0920** [comment]
No problem.

Could you review PR #6?
I've rebased with latest HEAD.

**Pull request closed without merging**
